language: python

python:
  - 2.7

sudo: true

services:
  - docker

before_install:
  - docker pull epahomov/docker-zeppelin
  - docker run -d -p 8080:8080 -p 7077:7077 -p 4040:4040 epahomov/docker-zeppelin
  - docker ps -a

# command to install dependencies
install:
  - pip install requests

# command to run tests
script:
  - sleep 10
  - netstat -ltpn
  - curl -i http://localhost:8080
  - python test.py

# tasks to execute after successful test
after_success:
  - echo "successful"
