language: python

python:
  - 2.7

sudo: true

services:
  - docker

before_install:
  - docker pull xemuliam/zeppelin
  - docker run -d -p 8080:8088 -p 8443:8443 xemuliam/zeppelin
  - docker ps -a

# command to install dependencies
install:
  - pip install requests

# command to run tests
script:
  - sleep 60
  - sudo netstat -ltpn
  - echo aa | nc  localhost 8088
  - curl -i http://localhost:8088
  - python test.py

# tasks to execute after successful test
after_success:
  - echo "successful"
